### PR TITLE
Added flex-box utility class for justify-content value `space-evenly`

### PR DESCRIPTION
**Pull request by mansguiche**
#67

### CODE REVIEW

**Comment by halfmoonui** [comment]
Hey, thank you for the PR. Sorry for getting back to this so late, I was taking a break. Anyway, let me review the code and the compatibility first before making any other adjustments.

**Comment by halfmoonui** [comment]
This particular CSS property seems to have around 95% compatibility at this moment, which is acceptable. Would you kindly make the same changes to the `halfmoon-variables.css` file please? I can create another branch and merge it there. I have been meaning to create a dev branch for some time, so I can put out the work I have done for `v1.2.0`, so we can start with this PR.

**Comment by mansguiche** [comment]
Sorry for the delay in getting back to you. I have made the requested changes to the `halfmoon-variables.css` file. Let me know if there are any more changes you require to this pull request.

**Comment by KaKi87** [comment]
Hello, in which version of halfmoon has this PR been released ? Thanks

**Comment by Toby222** [comment]
As it was merged in december and the lastest version came out a bit over 2 months earlier, I'd presume this is still "next release"

**Pull request merged**
