### PR TITLE
Make transitions look nicer

### PR DESCRIPTION
**Pull request by toman222**
The look of dark theme transition is really bothering me, so I made some amendments.

### CODE REVIEW

**Comment by halfmoonui** [comment]
Thank you for the PR. I am bit hesitant to merge this because it seems like an incomplete solution. For example, try switching modes on Firefox with custom scrollbars on the sidebar, and you will see that only the scrollbar lags behind. 

I think a better fix to this transition issue would be applying the transitions selectively only for the properties that require them.

**Comment by toman222** [comment]
True enough
This was just a quick fix, I'd be glad to modify it so that other transitions work, too.
I'd only need to know which values are meant to transition smoothly as opposed to instantly?

**Comment by toman222** [comment]
Also, is there an actual minifier I can use for the .css? This was just done by find-and-replacing the current one

**Comment by halfmoonui** [comment]
@toman222 I actually fixed this last night after writing the comment. Give me some time, I will commit the changes and push out a new release as soon as possible.

**Comment by toman222** [comment]
Nice.
PR not needed then, I suppose 👍

**Pull request closed without merging**
